(fn f [n]
  (cond
    (>= n 1000) (str "M"  (f (- n 1000)))
    (>= n 900)  (str "CM" (f (- n 900)))
    (>= n 500)  (str "D"  (f (- n 500)))
    (>= n 400)  (str "CD" (f (- n 400)))
    (>= n 100)  (str "C"  (f (- n 100)))
    (>= n 90)   (str "XC" (f (- n 90)))
    (>= n 50)   (str "L"  (f (- n 50)))
    (>= n 40)   (str "XL" (f (- n 40)))
    (>= n 10)   (str "X"  (f (- n 10)))
    (>= n 9)    (str "IX" (f (- n 9)))
    (>= n 5)    (str "V"  (f (- n 5)))
    (>= n 4)    (str "IV" (f (- n 4)))
    (>= n 1)    (str "I"  (f (- n 1)))
    :else       ""))
